#!/bin/bash
ln --force -s ~/dotfiles/homeroot/bashrc ~/.bashrc
ln --force -s ~/dotfiles/homeroot/profile ~/.profile
ln --force -s ~/dotfiles/homeroot/tmux ~/.tmux
ln --force -s ~/dotfiles/git/config ~/.gitconfig
./solarized/gnome-terminal/install.sh
