#!/bin/bash
ln --force -s ~/dotfiles/homeroot/bashrc ~/.bashrc
ln --force -s ~/dotfiles/homeroot/profile ~/.profile
cp ~/dotfiles/homeroot/gitconfig ~/.gitconfig
./solaralize/gnome-terminal/install.sh
