#!/bin/bash
cd $HOME/dotfiles
path_to_submodule=vim/bundle/$1
escaped=\"$path_to_submodule\"
echo $path_to_submodule

git config -f .gitmodules --remove-section submodule.$escaped

# Delete the relevant section from .git/config

git config -f .git/config --remove-section submodule.$escaped

# Unstage and remove $path_to_submodule only from the index (to prevent losing information)

git rm --cached -f $path_to_submodule

# Track changes made to .gitmodules

#git add .gitmodules

# Commit the superproject

#git commit -m "Remove submodule submodule_name"

# Delete the now untracked submodule files

rm -rf $path_to_submodule

#rm -rf .git/modules/$path_to_submodule
